Allow to always reload stacks from json file
fabric8io/fabric8-online pull request #252
Opened 2017-06-29 14:23 UTC by benoitf

### What does this PR do?
Policy on loading stacks has been changed. In order to keep previous policy, a flag needs to be set

### What issues does this PR fix or reference?
https://github.com/redhat-developer/rh-che/issues/124

#### Changelog
Update policy for loading stacks.json file

Change-Id: Ia2afc2460e3d5892d9bd1e32f719fe785387b610
Signed-off-by: Florent BENOIT <fbenoit@redhat.com>

2017-06-29 15:20 UTC, davidfestal requested changes
Don't you have to change the `cm.yaml`  to add the property also ? Else this might break in production if the config-map value is not found. 

Also it seems to me that you should add the value in the config map on `rh-che#master/dev-scripts/minishif-deploy.sh`. Else as soon as people update the `fabric-online` repo while being on `rh-che#master` they won't be able to deploy anymore.

2017-06-29 15:37 UTC, benoitf commented
@davidfestal yes for rh-che master I've also provided a PR https://github.com/redhat-developer/rh-che/pull/160
(At first it targeted master then @sunix wanted to have it for a branch, so now it ended up with two PR)

2017-06-29 15:39 UTC, benoitf commented
@davidfestal based on your feedback, I've added property on `cm.yaml`

2017-06-29 15:46 UTC, davidfestal commented
Thanks @benoitf

2017-06-29 15:47 UTC, davidfestal approved these changes

2017-07-03 08:25 UTC, l0rd approved these changes

2017-07-03 08:30 UTC, l0rd commented
[merge]

2017-07-03 08:31 UTC, merged