rh-che-212: store logs of che-server in a persistent volume
fabric8io/fabric8-online pull request #327
Opened 2017-07-26 14:36 UTC by benoitf

It will require https://github.com/redhat-developer/rh-che/pull/229 before merge

Change-Id: Ifad2b7e9e30642c9f3e472568063f06093abc716
Signed-off-by: Florent BENOIT <fbenoit@redhat.com>

2017-07-26 14:36 UTC, benoitf commented
@l0rd

2017-07-27 14:34 UTC, l0rd requested changes

2017-07-27 14:34 UTC, l0rd commented on apps/che/src/main/fabric8/deployment.yml
> +              key: "che.logs.dir"
@benoitf I think that you need to add `che.logs.dir` to cm.yml too

2017-07-27 15:29 UTC, benoitf commented on apps/che/src/main/fabric8/deployment.yml
> +              key: "che.logs.dir"
Added

2017-07-27 15:31 UTC, l0rd approved these changes
Thank you @benoitf LGTM

2017-07-27 15:32 UTC, l0rd commented
[merge]

2017-07-27 15:32 UTC, merged